In [2]:
import numpy as np

array1 = np.array([[10, 8], [3, 5]])

In [3]:
# 1.

inv_array1 = np.linalg.inv( array1 )
print(inv_array1)

Test = np.dot(inv_array1 , array1 )   # 是單位矩陣!!
print(Test)

[[ 0.19230769 -0.30769231]
 [-0.11538462  0.38461538]]
[[1. 0.]
 [0. 1.]]


In [4]:
# 2.

eigenvalues , eigenvectors = np.linalg.eig(array1)

print(eigenvalues)
print(eigenvectors)

[13.  2.]
[[ 0.93632918 -0.70710678]
 [ 0.35112344  0.70710678]]


In [7]:
# 3.

u , s , vh = np.linalg.svd(array1)

print(u)
print(s)
print(vh)

[[-0.91663818 -0.39971796]
 [-0.39971796  0.91663818]]
[13.94721714  1.86417116]
[[-0.74319741 -0.6690722 ]
 [-0.6690722   0.74319741]]
