In [1]:
import numpy as np

name_list = ['小明','小華','小菁','小美','小張','John','Mark','Tom']

sex_list = ['boy','boy','girl','girl','boy','boy','boy','boy']

weight_list = [67.5,75.3,50.1,45.5,80.8,90.4,78.4,70.7]

rank_list = [8,1,5,4,7,6,2,3]

myopia_list = [True,True,False,False,True,True,False,False]



In [6]:
# 1.

dt = np.dtype({'names' : ('name','sex','weight','rank','myopia'), 'formats' : ((np.str_,4),(np.str_,4),'f8','i8','?')})

students = np.zeros(8,dtype = dt)

students

array([('', '', 0., 0, False), ('', '', 0., 0, False),
       ('', '', 0., 0, False), ('', '', 0., 0, False),
       ('', '', 0., 0, False), ('', '', 0., 0, False),
       ('', '', 0., 0, False), ('', '', 0., 0, False)],
      dtype=[('name', '<U4'), ('sex', '<U4'), ('weight', '<f8'), ('rank', '<i8'), ('myopia', '?')])

In [7]:
students['name'] = name_list
students['sex'] = sex_list
students['weight'] = weight_list
students['rank'] = rank_list
students['myopia'] = myopia_list

print(students)

[('小明', 'boy', 67.5, 8,  True) ('小華', 'boy', 75.3, 1,  True)
 ('小菁', 'girl', 50.1, 5, False) ('小美', 'girl', 45.5, 4, False)
 ('小張', 'boy', 80.8, 7,  True) ('John', 'boy', 90.4, 6,  True)
 ('Mark', 'boy', 78.4, 2, False) ('Tom', 'boy', 70.7, 3, False)]


In [9]:
# 2.

print(students['weight'])

print('average weight is : ', np.average(students['weight']))

[67.5 75.3 50.1 45.5 80.8 90.4 78.4 70.7]
average weight is :  69.8375


In [12]:
# 3.

students[students['sex'] == 'boy']['weight']  students[students['sex'] == 'girl']['weight']

array([67.5, 75.3, 80.8, 90.4, 78.4, 70.7])

In [13]:
students[students['sex'] == 'girl']['weight']

array([50.1, 45.5])

In [15]:
print('average weight of boys is : ', np.average(students[students['sex'] == 'boy']['weight']))
print('average weight of girls is : ', np.average(students[students['sex'] == 'girl']['weight']))

average weight of boys is :  77.18333333333332
average weight of girls is :  47.8
